"use client";

import { useEffect, useState } from "react";
import { AuthGuard } from "@/components/layout/auth-guard";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { Card } from "@/components/ui/card";
import { apiFetch, getToken } from "@/lib/api";

export default function InsightsPage() {
  const [insights, setInsights] = useState<{
    key_bottlenecks: string[];
    high_risk_regions: string[];
    technician_load_alerts: string[];
    critical_backlog: number;
    risk_orders_next_hours: number;
  } | null>(null);

  useEffect(() => {
    const token = getToken();
    apiFetch("/api/v1/dashboard/executive-insights", {}, token).then(setInsights).catch(console.error);
  }, []);

  return (
    <AuthGuard>
      <DashboardShell>
        <Card>
          <h1 className="font-display text-xl font-bold">Executive Insights</h1>
          <p className="mt-1 text-sm text-slate-500">Aggregated bottlenecks and operational priorities generated by the Executive Report Agent.</p>

          {insights && (
            <div className="mt-5 grid gap-4 md:grid-cols-2">
              <div className="rounded-xl border border-slate-200 p-4">
                <h2 className="font-semibold">Top Bottlenecks</h2>
                <ul className="mt-2 space-y-1 text-sm text-slate-600">
                  {insights.key_bottlenecks.map((b) => <li key={b}>{b}</li>)}
                </ul>
              </div>
              <div className="rounded-xl border border-slate-200 p-4">
                <h2 className="font-semibold">High Risk Regions</h2>
                <p className="mt-2 text-sm text-slate-600">{insights.high_risk_regions.join(", ") || "No hot spots right now"}</p>
              </div>
              <div className="rounded-xl border border-slate-200 p-4">
                <h2 className="font-semibold">Technician Load Alerts</h2>
                <ul className="mt-2 space-y-1 text-sm text-slate-600">
                  {insights.technician_load_alerts.map((b) => <li key={b}>{b}</li>)}
                </ul>
              </div>
              <div className="rounded-xl border border-slate-200 p-4">
                <h2 className="font-semibold">Critical Backlog</h2>
                <p className="mt-2 text-2xl font-bold">{insights.critical_backlog}</p>
                <p className="text-sm text-slate-500">Orders at risk in the next hours: {insights.risk_orders_next_hours}</p>
              </div>
            </div>
          )}
        </Card>
      </DashboardShell>
    </AuthGuard>
  );
}
